export const DEFAULT_VIEWER_CONFIG = {
  MIN_ZOOM: 0.5,
  MAX_ZOOM: 3,
  DEFAULT_QR_SIZE: 20,
  DEFAULT_DPI: 300,
  ZOOM_STEP: 0.25,
  ROTATION_STEP: 90,
  DEFAULT_VIEWER_HEIGHT: "calc(100vh - 300px)",
};
